language: node_js
node_js: 
  - "10.11.0"
cache:
  directories:
    - "node_modules"
after_success:
  - git branch
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy # this key should have push access
  - ssh-add .travis/deploy
  - git remote add deploy administrator@tga.ecti.ac.nz:/home/administrator/trials/repo
  - git push deploy
